# Generated by Django 6.0.4 on 2026-05-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('project_type', models.CharField(choices=[('under_500', 'Under $500'), ('500_1000', '$500 - $1000'), ('1000_5000', '$1000 - $5000'), ('5000_plus', '$5000+'), ('custom', 'Custom')], max_length=50)),
                ('budget', models.CharField(choices=[('under_500', 'Under $500'), ('500_1000', '$500 - $1000'), ('1000_5000', '$1000 - $5000'), ('5000_plus', '$5000+'), ('custom', 'Custom')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
