# Generated by Django 6.0.4 on 2026-05-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='project_type',
            field=models.CharField(choices=[('django', 'Django Development'), ('api', 'API Development'), ('automation', 'Business Automation'), ('consulting', 'Consulting'), ('other', 'Other')], max_length=50),
        ),
    ]
