# Generated by Django 6.0.4 on 2026-05-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactform_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contactmodel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
